# Site settings
title: Anna Liz Jensen
twitter_username: ajyells
name: Anna Liz Jensen

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/annalizjensen
 - title: LinkedIn
   url: https://www.linkedin.com/in/annalizjensen
 - title: Flipboard
   url: https://flipboard.com/@flipjensen

#Any buzzword skills you want to include
skills:
 - Java
 - Scala
 - Python
 - Bash
 - Gradle/Groovy
 - Jenkins CI
 - AWS
 - SQL
 - HBase
 - Technical Leadership
 - People Management
 - Hiring Management
 - Company-wide event organization
 - Creative and technical writing
 - Public speaking
 - Mentorship & communication

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
# blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Manager, Core Applications team
   start: 2020
   end: Ongoing
   employer: Flipboard
   description: I lead a team of six engineers on our Core Apps team. The team is responsible for development and maintenance of our core API functionality. My day-to-day involves working with product and business teams to design technical products and leading a technical team to bringing those architecture documents to life. 
 - title: Software Engineer
   start: 2018
   end: 2020
   employer: Flipboard
   description: As a software engineer I have worked largely in the JVM to functionality and scalability to our central APIs. I worked on several major features in this role, most notably with Samsung Daily Card, Flipboard TV, Storyboards, and spam & abuse detection services.
 - title: Associate Software Engineer
   start: 2017
   end: 2018
   employer: Flipboard
   description: I worked on a variety of projects in both Python and Scala, most notably, Flipboard's Briefing+ product, which shipped on Samsung devices.
 - title: Software Engineering Intern
   start: 2016
   end: 2016
   employer: Flipboard
   description: I contributed to our media web crawler and designed and implemented a error reporting and aggregation UI for our publisher support team.
 - title: Special Projects Intern
   start: 2015
   end: 2015
   employer: Swarthmore College
   description: I worked on a variety of web development projects proposed by professors to further their research goals.
   
#Education is required
education:
 - level: Bachelor of Arts
   date: 2017
   subject: Computer Science
   school: Swarthmore College

intro: |
  Hi there! I’m a skilled software developer in the Bay Area interested in crafting delightful user experiences, building efficient and scalable software, and leading technical teams to success. I currently work at Flipboard, where I'm an engineering manager on our Core Applications team. I have primarily worked in the JVM (Java, Scala, very minor Clojure and Kotlin experience) within a microservices architecture, but I have worked across codebases throughout my career and have learned to pick the right tool for the job.
